name: CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run the tests
        run: bazel test -j 4 //...

  cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache CMake FetchContent dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/build/_deps
          key: ${{ runner.os }}-cmake-deps-poto-${{ matrix.protobuf-version }}-googletest-${{ matrix.googletest-version }}
          restore-keys: |
            ${{ runner.os }}-cmake-deps-
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@1bbbcda0748b3e340dee71a314fa68ffcbd6df79 # v1.2.21
        with:
          key: ${{ runner.os }}
          max-size: 500M
      - name: Set up CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      - name: Run build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cmake --build build --target test
