name: CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run the tests
        run: bazel test -j 4 //...

  cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up CMake
        run: |
          cmake -S . -B build -G Ninja
      - name: Run build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cmake --build build --target test
